development:
  :concurrency: 5
production:
  :concurrency: 16
:queues:
  - critical
  - default
  - communication

:scheduler:
  # Tells Sidekiq that for each worker process to only listen to the queues I tell it to in the launch Procfile
  :listened_queues_only: true